// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication4.Models
{
    public partial class book
    {
        [Key]
        public int? id { get; set; }
        [StringLength(300)]
        public string? title { get; set; }
        [StringLength(300)]
        public string bref { get; set; }
        public string desc { get; set; }
        [StringLength(300)]
        public string img { get; set; }
        public int? student_id { get; set; }
        public int? cat_id { get; set; }
        [Column("date", TypeName = "DateTime")]
        public DateTime? date { get; set; }
        
        
        [ForeignKey("cat_id")]
        [InverseProperty("books")]
        public virtual catalog cat { get; set; }
        [ForeignKey("student_id")]
        [InverseProperty("books")]
        public virtual student student { get; set; }
    }
}